### PR TITLE
Add QC workflow action

### PR DESCRIPTION
**Pull request by caufieldjh**
This adds a workflow for preparing builds for different architectures and, eventually (i.e., once #2 is merged), running tests.

### CODE REVIEW

**Comment by caufieldjh** [comment]
Will need to specify python versions starting at 3.7. May not need to go all the way to 3.10.

**Comment by caufieldjh** [comment]
Use this for reference: https://github.com/messense/py-dissimilar/blob/86bb5e95826d9818a02b4a9f67c3d41be5df3760/.github/workflows/CI.yml

**Comment by caufieldjh** [comment]
Linux build is still defaulting to Python 3.6 - try something like https://github.com/messense/py-dissimilar/blob/86bb5e95826d9818a02b4a9f67c3d41be5df3760/.github/workflows/CI.yml#L124

**Comment by caufieldjh** [comment]
Also not passing Pypi authentication just yet

**Comment by caufieldjh** [comment]
For some reason this takes a loooong time to build for macos + aarch64, like >1 hr

**Comment by caufieldjh** [comment]
Based on this: https://github.com/PyO3/maturin/pull/1356
The `aarch64` target could be switched out for `universal2` to build for macos Arm64.

**Comment by caufieldjh** [comment]
Ah, this probably isn't helping (running out of space on the actions node):
```
Prepare macOS universal2 build environment
/Users/runner/work/_temp/e851d4a8-8447-4604-b5cf-1720ae1aec58/maturin build --release --universal2 --out dist --sdist -i 3.7 3.8 3.9 pypy3.8 pypy3.9
🔗 Found pyo3 bindings
🐍 Found CPython 3.7m, CPython 3.8, CPython 3.9, PyPy 3.8, PyPy 3.9
💥 maturin failed
  Caused by: Failed to build source distribution
  Caused by: Failed to add file from /Users/runner/work/rustsim/rustsim/dist/rustsim-0.1.0.tar.gz to sdist as rustsim-0.1.0/dist/rustsim-0.1.0.tar.gz
  Caused by: failed to write to file `dist/rustsim-0.1.0.tar.gz`
  Caused by: No space left on device (os error [28](https://github.com/Knowledge-Graph-Hub/rustsim/actions/runs/4148352911/jobs/7176259090#step:7:32))
Error: The process '/Users/runner/work/_temp/e851d4a8-8[44](https://github.com/Knowledge-Graph-Hub/rustsim/actions/runs/4148352911/jobs/7176259090#step:7:48)7-4604-b5cf-1720ae1aec58/maturin' failed with exit code 1
    at ExecState._setResult (/Users/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1702:25)
    at ExecState.CheckComplete (/Users/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/Users/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1579:27)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:[45](https://github.com/Knowledge-Graph-Hub/rustsim/actions/runs/4148352911/jobs/7176259090#step:7:49)1:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
Error: The process '/Users/runner/work/_temp/e851d4a8-8447-4604-b5cf-1720ae1aec58/maturin' failed with exit code 1
```

**Comment by justaddcoffee** [comment]
Looking at the failing macos build: we don't need to build source distributions do we?  

> /Users/runner/work/_temp/e851d4a8-8447-4604-b5cf-1720ae1aec58/maturin build --release --universal2 --out dist --sdist -i 3.7 3.8 3.9 pypy3.8 pypy3.9
> 🔗 Found pyo3 bindings
> 🐍 Found CPython 3.7m, CPython 3.8, CPython 3.9, PyPy 3.8, PyPy 3.9
> 💥 maturin failed
>  Caused by: Failed to build source distribution
>  Caused by: Failed to add file from /Users/runner/work/rustsim/rustsim/dist/rustsim-0.1.0.tar.gz to sdist as rustsim-0.1.0/dist/rustsim-0.1.0.tar.gz
>  Caused by: failed to write to file `dist/rustsim-0.1.0.tar.gz`

**Comment by caufieldjh** [comment]
No, we don't need those. Will try the build without them.

**Pull request merged**
